---

- name: install cosmovisor
  command: "go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@{{ cosmovisor_release }}"
  environment:
    PATH: "{{ path.stdout }}:{{ gopaths.stdout }}"

- name: make cosmovisor directories 
  file:
    path: "{{ gaia_home_dir }}/cosmovisor/genesis/bin"
    state: directory

- name: make cosmovisor directories 
  copy:
    src: "{{ ansible_env.HOME }}/go/bin/gaiad"
    dest: "{{ gaia_home_dir }}/cosmovisor/genesis/bin/gaiad"
    mode: "0755"
    remote_src: true
